
-- Backfill body_part from title keywords where empty
UPDATE blogs SET body_part = CASE
  WHEN body_part IS NOT NULL AND body_part <> '' THEN body_part
  WHEN title ~* 'shoulder|rotator cuff|frozen shoulder|impingement|bursitis' THEN 'Shoulder'
  WHEN title ~* 'elbow|tennis elbow|golfer''s elbow|epicondyl' THEN 'Elbow'
  WHEN title ~* 'wrist|carpal|hand|finger|thumb|de quervain' THEN 'Wrist/Hand'
  WHEN title ~* 'neck|cervical|whiplash|text neck|torticollis' THEN 'Neck'
  WHEN title ~* 'thoracic|upper back|scapul|dowager|kyphos' THEN 'Upper Back'
  WHEN title ~* 'low back|lumbar|sciatica|disc|si joint|sacroiliac|piriformis|spondyl' THEN 'Lower Back'
  WHEN title ~* 'hip|trochanter|labral|femor|glute' THEN 'Hip'
  WHEN title ~* 'knee|acl|mcl|meniscus|patell|jumper''s|runner''s knee|osgood' THEN 'Knee'
  WHEN title ~* 'ankle|foot|achilles|plantar|heel|arch|calf|shin|toe' THEN 'Ankle/Foot'
  WHEN title ~* 'jaw|tmj|headache|migrain|facial|vestibul|vertigo|bppv|concussion' THEN 'Head/Face'
  WHEN title ~* 'chest|rib|thorax|breath|lung|copd|asthma|pulmon|cardiac|heart' THEN 'Chest'
  WHEN title ~* 'pelvic|groin|adductor|incontinence|prostat|postnatal|pregnan' THEN 'Pelvis'
  WHEN title ~* 'stroke|parkinson|multiple sclerosis|spinal cord|neuropathy|nerve|balance|gait|fall' THEN 'Full Body'
  WHEN title ~* 'amputee|prosthet|arthritis|fibromyalgia|osteoporo|cancer|pediatric|geriatric|posture|ergonom' THEN 'Full Body'
  ELSE 'Full Body'
END
WHERE cover_image_url IS NOT NULL OR cover_image_url IS NULL;

-- Rewrite cover_image_url with unique medical/anatomical imagery per article.
-- Uses loremflickr with body-part-specific + medical/anatomy tags.
-- Unique per-row seed derived from the article's UUID guarantees no collisions.
UPDATE blogs SET
  cover_emoji = NULL,
  cover_image_url = 'https://loremflickr.com/1200/800/'
    || CASE
      -- Highly specific title-driven keywords first
      WHEN title ~* 'sciatica|piriformis'          THEN 'sciatica,nerve,spine,anatomy,medical'
      WHEN title ~* 'disc|herniat|bulging'         THEN 'spinal-disc,mri,spine,anatomy,medical'
      WHEN title ~* 'lumbar|low back'              THEN 'lumbar-spine,xray,anatomy,medical'
      WHEN title ~* 'cervical|neck|whiplash|text neck|torticollis' THEN 'cervical-spine,neck,anatomy,medical'
      WHEN title ~* 'thoracic|upper back|scapul|kyphos' THEN 'thoracic-spine,xray,anatomy,medical'
      WHEN title ~* 'si joint|sacroiliac'          THEN 'sacrum,pelvis,anatomy,medical'
      WHEN title ~* 'frozen shoulder'              THEN 'frozen-shoulder,anatomy,medical,xray'
      WHEN title ~* 'rotator cuff|impingement'     THEN 'rotator-cuff,shoulder,anatomy,medical'
      WHEN title ~* 'bursitis'                     THEN 'bursitis,joint,inflammation,medical'
      WHEN title ~* 'shoulder'                     THEN 'shoulder-joint,anatomy,xray,medical'
      WHEN title ~* 'tennis elbow|lateral epicondyl' THEN 'tennis-elbow,elbow,anatomy,medical'
      WHEN title ~* 'golfer''s elbow|medial epicondyl' THEN 'elbow,anatomy,medical,xray'
      WHEN title ~* 'elbow'                        THEN 'elbow-joint,anatomy,xray,medical'
      WHEN title ~* 'carpal tunnel'                THEN 'carpal-tunnel,wrist,nerve,anatomy'
      WHEN title ~* 'de quervain'                  THEN 'wrist,tendon,anatomy,medical'
      WHEN title ~* 'wrist|hand|finger|thumb'      THEN 'hand,wrist,xray,anatomy,medical'
      WHEN title ~* 'acl'                          THEN 'acl,knee-ligament,anatomy,medical'
      WHEN title ~* 'meniscus'                     THEN 'meniscus,knee,mri,anatomy,medical'
      WHEN title ~* 'patell|jumper''s knee|runner''s knee' THEN 'patella,knee-cap,anatomy,medical'
      WHEN title ~* 'osgood'                       THEN 'knee,tibia,pediatric,anatomy,medical'
      WHEN title ~* 'knee'                         THEN 'knee-joint,anatomy,xray,medical'
      WHEN title ~* 'trochanter|greater trochanter' THEN 'hip,trochanter,anatomy,medical'
      WHEN title ~* 'labral|hip'                   THEN 'hip-joint,anatomy,xray,medical'
      WHEN title ~* 'glute'                        THEN 'gluteus,muscle,anatomy,medical'
      WHEN title ~* 'achilles'                     THEN 'achilles-tendon,ankle,anatomy,medical'
      WHEN title ~* 'plantar|heel|arch'            THEN 'plantar-fascia,foot,anatomy,medical'
      WHEN title ~* 'shin|calf'                    THEN 'calf,tibia,muscle,anatomy,medical'
      WHEN title ~* 'ankle|foot|toe'               THEN 'ankle-foot,anatomy,xray,medical'
      WHEN title ~* 'tmj|jaw'                      THEN 'jaw,tmj,skull,anatomy,medical'
      WHEN title ~* 'headache|migrain'             THEN 'brain,headache,neurology,medical'
      WHEN title ~* 'vestibul|vertigo|bppv'        THEN 'inner-ear,vestibular,anatomy,medical'
      WHEN title ~* 'concussion'                   THEN 'brain,mri,neurology,medical'
      WHEN title ~* 'stroke'                       THEN 'brain,stroke,neurology,medical'
      WHEN title ~* 'parkinson'                    THEN 'brain,neurons,neurology,medical'
      WHEN title ~* 'multiple sclerosis'           THEN 'nerve,myelin,neurology,medical'
      WHEN title ~* 'spinal cord'                  THEN 'spinal-cord,anatomy,neurology,medical'
      WHEN title ~* 'neuropathy|nerve'             THEN 'peripheral-nerve,anatomy,neurology,medical'
      WHEN title ~* 'balance|gait|fall'            THEN 'balance,rehabilitation,physiotherapy,medical'
      WHEN title ~* 'copd|asthma|pulmon|breath|lung' THEN 'lungs,respiratory,anatomy,medical'
      WHEN title ~* 'cardiac|heart'                THEN 'heart,cardiology,anatomy,medical'
      WHEN title ~* 'rib|chest|thorax'             THEN 'ribcage,thorax,anatomy,medical'
      WHEN title ~* 'pelvic floor|incontinence'    THEN 'pelvis,pelvic-floor,anatomy,medical'
      WHEN title ~* 'pregnan|postnatal|prenatal'   THEN 'pregnancy,pelvis,anatomy,medical'
      WHEN title ~* 'groin|adductor'               THEN 'groin,adductor,anatomy,medical'
      WHEN title ~* 'prostat'                      THEN 'pelvis,anatomy,medical,urology'
      WHEN title ~* 'amputee|prosthet'             THEN 'prosthetic,rehabilitation,physiotherapy,medical'
      WHEN title ~* 'osteoporo'                    THEN 'bone,osteoporosis,xray,medical'
      WHEN title ~* 'arthritis|osteoarthritis|rheumat' THEN 'arthritis,joint,xray,medical'
      WHEN title ~* 'fibromyalgia'                 THEN 'muscle,pain,anatomy,medical'
      WHEN title ~* 'cancer|oncolog'               THEN 'oncology,radiology,medical,anatomy'
      WHEN title ~* 'diabet'                       THEN 'diabetes,medical,anatomy'
      WHEN title ~* 'pediatric|child'              THEN 'pediatric,physiotherapy,rehabilitation,medical'
      WHEN title ~* 'geriatric|elderly'            THEN 'geriatric,physiotherapy,rehabilitation,medical'
      WHEN title ~* 'posture|ergonom'              THEN 'posture,spine,ergonomics,anatomy,medical'
      WHEN title ~* 'stretch|mobility|flexibil'    THEN 'stretching,physiotherapy,muscle,anatomy'
      WHEN title ~* 'strength|resistance'          THEN 'muscle,strength,anatomy,medical'
      WHEN title ~* 'running|athlete|sport'        THEN 'sports-medicine,anatomy,physiotherapy,medical'
      WHEN title ~* 'yoga'                         THEN 'yoga-therapy,anatomy,physiotherapy,medical'
      WHEN title ~* 'massage|manual|myofascia|trigger point' THEN 'manual-therapy,physiotherapy,muscle,anatomy'
      WHEN title ~* 'dry needling|acupunc'         THEN 'dry-needling,physiotherapy,anatomy,medical'
      WHEN title ~* 'taping|kinesio'               THEN 'kinesio-tape,physiotherapy,anatomy,medical'
      WHEN title ~* 'ultrasound|electrotherapy|tens' THEN 'ultrasound-therapy,physiotherapy,medical'
      WHEN title ~* 'ice|cryo|heat'                THEN 'therapy,physiotherapy,recovery,medical'
      WHEN title ~* 'assessment|examination|diagnos' THEN 'clinical-assessment,physiotherapy,anatomy,medical'
      WHEN title ~* 'rehabilitation|recovery|post-surg|post surgery' THEN 'rehabilitation,physiotherapy,anatomy,medical'
      ELSE 'physiotherapy,anatomy,muscle,skeleton,medical'
    END
    || '?lock=' || (('x' || substr(md5(id::text), 1, 8))::bit(32)::int)::text;
